[rocks]

[plugins]
"rocks.nvim" = "2.40.2"
"rocks-config.nvim" = "3.0.0"
"rocks-git.nvim" = "2.3.1"
"gitsigns.nvim" = "0.9.0"
nvim-autopairs = "scm"
nvim-treesitter-context = "scm"
tree-sitter-python = "0.0.28"

[config]
auto_setup = true
